### ISSUE TITLE
Selecting common/latin removes species distro tiles

### ISSUE THREAD

**Issue by tpcolson** [grsmgis/npmap-species#4]
![image](https://user-images.githubusercontent.com/5861784/144432992-d9fcfad6-6884-4bd3-9b4a-c126484b28a0.png)
In this screen shot, check latin, distro tiles are removed?
![image](https://user-images.githubusercontent.com/5861784/144433120-3b8c4c4b-5d50-4894-9be0-facc96c19522.png)

**Comment by branson2015** [comment]
bbf3f29b94be2b1106b54c87542e39205795f0c8 closes

**Comment by JustAnotherJames** [comment]
bbf3f29b94be2b1106b54c87542e39205795f0c8 Closes.
